/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    BasicExample: typeof import('./components/BasicExample.vue')['default']
    CellMergeExample: typeof import('./components/CellMergeExample.vue')['default']
    ColumnResizeExample: typeof import('./components/ColumnResizeExample.vue')['default']
    Comprehensive: typeof import('./components/Comprehensive.vue')['default']
    CustomSlotExample: typeof import('./components/CustomSlotExample.vue')['default']
    CustomTheme: typeof import('./components/CustomTheme.vue')['default']
    EditStateExample: typeof import('./components/EditStateExample.vue')['default']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ExpandableExample: typeof import('./components/ExpandableExample.vue')['default']
    FixedColumnsExample: typeof import('./components/FixedColumnsExample.vue')['default']
    FixedHeaderExample: typeof import('./components/FixedHeaderExample.vue')['default']
    PaginationExample: typeof import('./components/PaginationExample.vue')['default']
    PerformanceComparison: typeof import('./components/PerformanceComparison.vue')['default']
    RowSelectionExample: typeof import('./components/RowSelectionExample.vue')['default']
    SortFilterExample: typeof import('./components/SortFilterExample.vue')['default']
    SummaryExample: typeof import('./components/SummaryExample.vue')['default']
    TreeDataExample: typeof import('./components/TreeDataExample.vue')['default']
  }
}
